
package swingkids;

import javax.swing.JOptionPane;
import javax.swing.JLabel;
 
/**
 *
 * @author rafaelblancoaranda
 */
public class GameMenu extends javax.swing.JFrame {

    
    /**
     * Creates new form GameMenu1
     */
    public GameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOutButton = new javax.swing.JPanel();
        jLabelLogOut = new javax.swing.JLabel();
        leaderboardIcon = new javax.swing.JLabel();
        leaderboardButton = new javax.swing.JPanel();
        leaderboardLabel = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        playButton = new javax.swing.JPanel();
        playLabel = new javax.swing.JLabel();
        logOutIcon = new javax.swing.JLabel();
        playIcon = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOutButton.setBackground(new java.awt.Color(255, 255, 204));
        logOutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        logOutButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        jLabelLogOut.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabelLogOut.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.jLabelLogOut.text")); // NOI18N
        logOutButton.add(jLabelLogOut);

        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, -1));

        leaderboardIcon.setIcon(new javax.swing.ImageIcon("/Users/rafaelblancoaranda/Downloads/estrella.png")); // NOI18N
        leaderboardIcon.setLabelFor(leaderboardButton);
        leaderboardIcon.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.leaderboardIcon.text")); // NOI18N
        leaderboardIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderboardIconMouseClicked(evt);
            }
        });
        getContentPane().add(leaderboardIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        leaderboardButton.setBackground(new java.awt.Color(255, 204, 153));
        leaderboardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        leaderboardButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        leaderboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaderboardButtonMouseClicked(evt);
            }
        });

        leaderboardLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        leaderboardLabel.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.leaderboardLabel.text")); // NOI18N
        leaderboardButton.add(leaderboardLabel);

        getContentPane().add(leaderboardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoo (1).png"))); // NOI18N
        logo.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.logo.text")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 70, 70));

        title.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        title.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.title.text")); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 50));

        playButton.setBackground(new java.awt.Color(255, 204, 153));
        playButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        playButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
        });

        playLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        playLabel.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.playLabel.text")); // NOI18N
        playButton.add(playLabel);

        getContentPane().add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 100, 50));
        playButton.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.playButton.AccessibleContext.accessibleName")); // NOI18N

        logOutIcon.setIcon(new javax.swing.ImageIcon("/Users/rafaelblancoaranda/Downloads/left-arrow.png")); // NOI18N
        logOutIcon.setLabelFor(logOutButton);
        logOutIcon.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.logOutIcon.text")); // NOI18N
        logOutIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutIconMouseClicked(evt);
            }
        });
        getContentPane().add(logOutIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, 60));

        playIcon.setIcon(new javax.swing.ImageIcon("/Users/rafaelblancoaranda/Downloads/videogame.png")); // NOI18N
        playIcon.setLabelFor(playButton);
        playIcon.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.playIcon.text")); // NOI18N
        playIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playIconMouseClicked(evt);
            }
        });
        getContentPane().add(playIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        background.setBackground(new java.awt.Color(248, 248, 248));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mpm-retocao.png"))); // NOI18N
        background.setText(org.openide.util.NbBundle.getMessage(GameMenu.class, "GameMenu.background.text")); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
         
    }//GEN-LAST:event_backgroundMouseClicked

    private void leaderboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderboardButtonMouseClicked
       Leaderboard leaderboard= new Leaderboard(this, true);
       leaderboard.setVisible(true);
       
    }//GEN-LAST:event_leaderboardButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
       this.setVisible(false);
        new MainView().setVisible(true);
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        new AnimalMemoryGame().setVisible(true);
    }//GEN-LAST:event_playButtonMouseClicked

    private void playIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playIconMouseClicked
         new AnimalMemoryGame().setVisible(true);
    }//GEN-LAST:event_playIconMouseClicked

    private void leaderboardIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaderboardIconMouseClicked
        Leaderboard leaderboard= new Leaderboard(this, true);
       leaderboard.setVisible(true);
    }//GEN-LAST:event_leaderboardIconMouseClicked

    private void logOutIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutIconMouseClicked
      this.setVisible(false);
        new MainView().setVisible(true);
    }//GEN-LAST:event_logOutIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JPanel leaderboardButton;
    private javax.swing.JLabel leaderboardIcon;
    private javax.swing.JLabel leaderboardLabel;
    private javax.swing.JPanel logOutButton;
    private javax.swing.JLabel logOutIcon;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel playButton;
    private javax.swing.JLabel playIcon;
    private javax.swing.JLabel playLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
