
package swingkids;

import basededatos.GestorSwingKids;
import javax.swing.JLabel;

/**
 *
 * @author rafaelblancoaranda
 */
public class Leaderboard extends javax.swing.JDialog {

    /**
     * Creates new form Leaderboard
     */
    public Leaderboard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        GestorSwingKids gsk=new GestorSwingKids();
        score1.setText("     1.- "+gsk.getPuntuacionPorPosicionRanking(1));
        score2.setText("     2.- "+gsk.getPuntuacionPorPosicionRanking(2));
        score3.setText("     3.- "+gsk.getPuntuacionPorPosicionRanking(3));
        score4.setText("     4.- "+gsk.getPuntuacionPorPosicionRanking(4));
        score5.setText("     5.- "+gsk.getPuntuacionPorPosicionRanking(5));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JTextField();
        scorePanel = new javax.swing.JPanel();
        blankSpace = new javax.swing.JTextArea();
        score1 = new javax.swing.JTextArea();
        score2 = new javax.swing.JTextArea();
        score3 = new javax.swing.JTextArea();
        score4 = new javax.swing.JTextArea();
        score5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setEditable(false);
        title.setBackground(new java.awt.Color(255, 204, 153));
        title.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title.setText(org.openide.util.NbBundle.getMessage(Leaderboard.class, "Leaderboard.title.text")); // NOI18N
        title.setToolTipText(org.openide.util.NbBundle.getMessage(Leaderboard.class, "Leaderboard.title.toolTipText")); // NOI18N
        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        title.setSelectionColor(new java.awt.Color(153, 153, 255));
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleKeyPressed(evt);
            }
        });
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

        scorePanel.setBackground(new java.awt.Color(255, 255, 204));
        scorePanel.setPreferredSize(new java.awt.Dimension(630, 630));
        scorePanel.setLayout(new java.awt.GridLayout(6, 6, 5, 5));

        blankSpace.setEditable(false);
        blankSpace.setBackground(new java.awt.Color(255, 255, 204));
        blankSpace.setColumns(20);
        blankSpace.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        blankSpace.setRows(5);
        blankSpace.setBorder(null);
        scorePanel.add(blankSpace);

        score1.setEditable(false);
        score1.setBackground(new java.awt.Color(255, 255, 204));
        score1.setColumns(20);
        score1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        score1.setRows(5);
        score1.setBorder(null);
        scorePanel.add(score1);

        score2.setEditable(false);
        score2.setBackground(new java.awt.Color(255, 255, 204));
        score2.setColumns(20);
        score2.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        score2.setRows(5);
        score2.setBorder(null);
        scorePanel.add(score2);

        score3.setEditable(false);
        score3.setBackground(new java.awt.Color(255, 255, 204));
        score3.setColumns(20);
        score3.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        score3.setRows(5);
        score3.setBorder(null);
        scorePanel.add(score3);

        score4.setEditable(false);
        score4.setBackground(new java.awt.Color(255, 255, 204));
        score4.setColumns(20);
        score4.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        score4.setRows(5);
        score4.setBorder(null);
        scorePanel.add(score4);

        score5.setEditable(false);
        score5.setBackground(new java.awt.Color(255, 255, 204));
        score5.setColumns(20);
        score5.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        score5.setRows(5);
        score5.setBorder(null);
        scorePanel.add(score5);

        getContentPane().add(scorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 280, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        setLocation(evt.getXOnScreen() - 300, evt.getYOnScreen());
    }//GEN-LAST:event_titleMouseDragged

    private void titleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleKeyPressed
        
    }//GEN-LAST:event_titleKeyPressed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Leaderboard dialog = new Leaderboard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea blankSpace;
    private javax.swing.JTextArea score1;
    private javax.swing.JTextArea score2;
    private javax.swing.JTextArea score3;
    private javax.swing.JTextArea score4;
    private javax.swing.JTextArea score5;
    private javax.swing.JPanel scorePanel;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
