
package swingkids;

import basededatos.GestorSwingKids;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculaValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.Lookup;




/**
 *
 * @author rafaelblancoaranda
 */
public class MainView extends javax.swing.JFrame {

    public static String userName;
    /**
     * Creates new form NewJFrame
     */
    public MainView() {
        initComponents();
        logInButton.setEnabled(false);
        ValidationGroup group=  mainValidation.getValidationGroup();
        group.add(passField,  StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(playerNameField, StringValidators.REQUIRE_NON_EMPTY_STRING, new MayusculaValidator());
        
        mainValidation.addChangeListener((ChangeEvent e) -> {
            if(mainValidation.getProblem()==null){
                logInButton.setEnabled(true);
            }else{
                logInButton.setEnabled(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainValidation = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        logo = new javax.swing.JLabel();
        playerNameLabel = new javax.swing.JLabel();
        playerNameField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        registerLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        registerLink = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        underlineLabel = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainValidation.setBackground(new java.awt.Color(248, 248, 248));
        mainValidation.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        getContentPane().add(mainValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 140));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoo (1).png"))); // NOI18N
        logo.setName(""); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 70, 80));

        playerNameLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        playerNameLabel.setLabelFor(playerNameField);
        playerNameLabel.setText("Nombre");
        getContentPane().add(playerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, 20));

        playerNameField.setBackground(new java.awt.Color(255, 204, 153));
        playerNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playerNameField.setName("Nombre"); // NOI18N
        playerNameField.setNextFocusableComponent(passField);
        getContentPane().add(playerNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 30));

        passLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        passLabel.setLabelFor(passField);
        passLabel.setText("Contraseña");
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        passField.setBackground(new java.awt.Color(255, 204, 153));
        passField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passField.setName("Contraseña"); // NOI18N
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 190, 30));

        registerLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        registerLabel.setText("¿No tienes cuenta? Regístrate ");
        getContentPane().add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        logInButton.setBackground(new java.awt.Color(255, 255, 204));
        logInButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        logInButton.setText("Iniciar Sesión");
        logInButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, 30));

        registerLink.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        registerLink.setText("aquí");
        registerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkMouseClicked(evt);
            }
        });
        getContentPane().add(registerLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 40, -1));

        title.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        title.setText("SwingKids");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, 60));

        underlineLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        underlineLabel.setText("___");
        getContentPane().add(underlineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 30, -1));

        backgroundImage.setBackground(new java.awt.Color(255, 255, 255));
        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mpm-retocao.png"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
       
        GestorSwingKids gsk1= new GestorSwingKids();
        MainView.userName=playerNameField.getText();
       if(gsk1.login(playerNameField.getText(),String.valueOf(passField.getPassword()))){
           new GameMenu().setVisible(true);
           this.setVisible(false);
       }else{
           LoginError loginError= new LoginError(this,true);
           loginError.setVisible(true);
           
       }
        
       
      
           
       
        
        
    }//GEN-LAST:event_logInButtonActionPerformed

    private void registerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkMouseClicked
        RegisterForm newRegister= new RegisterForm(this,true);
        newRegister.setVisible(true);
    }//GEN-LAST:event_registerLinkMouseClicked

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 Locale.setDefault(new Locale("es", "ES"));
                new MainView().setVisible(true);
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton logInButton;
    private javax.swing.JLabel logo;
    private org.netbeans.validation.api.ui.swing.ValidationPanel mainValidation;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField playerNameField;
    private javax.swing.JLabel playerNameLabel;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JLabel registerLink;
    private javax.swing.JLabel title;
    private javax.swing.JLabel underlineLabel;
    // End of variables declaration//GEN-END:variables
}
