



package swingkids;

import basededatos.Jugador;
import basededatos.GestorSwingKids;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import org.netbeans.validation.api.builtin.stringvalidation.MayusculaValidator;
import org.netbeans.validation.api.builtin.stringvalidation.PassWordValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author rafaelblancoaranda
 */
public class RegisterForm extends javax.swing.JDialog {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        registerButton.setEnabled(false);
        ValidationGroup group1=  nameAgeValidation.getValidationGroup();
        group1.add(ageField, StringValidators.REQUIRE_VALID_INTEGER, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_NON_NEGATIVE_NUMBER);
        group1.add(userNameField, StringValidators.REQUIRE_NON_EMPTY_STRING, new MayusculaValidator());
        
        ValidationGroup group2=  passValidation.getValidationGroup();
        
        group2.add(passField, new PassWordValidator());
        group2.add(pass2Field, new PassWordValidator());          
        
        passValidation.addChangeListener((ChangeEvent e) -> {
            if(nameAgeValidation.getProblem()==null && passValidation.getProblem()==null && (Arrays.equals(passField.getPassword(), pass2Field.getPassword()))){
                registerButton.setEnabled(true);
            }else{
                registerButton.setEnabled(false);
            }
        });
        
        nameAgeValidation.addChangeListener((ChangeEvent e) -> {
            if(nameAgeValidation.getProblem()==null && passValidation.getProblem()==null && (Arrays.equals(passField.getPassword(), pass2Field.getPassword()))){
                registerButton.setEnabled(true);
            }else{
                registerButton.setEnabled(false);
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        pass2Field = new javax.swing.JPasswordField();
        Pass2Label = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        passValidation = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        nameAgeValidation = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Comic Sans MS", 3, 36)); // NOI18N
        title.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.title.text")); // NOI18N
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zoo (1).png"))); // NOI18N
        logo.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.logo.text")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 70, 70));

        userNameLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        userNameLabel.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.userNameLabel.text")); // NOI18N
        getContentPane().add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, -1));

        userNameField.setBackground(new java.awt.Color(255, 204, 153));
        userNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userNameField.setName("Nombre"); // NOI18N
        userNameField.setNextFocusableComponent(ageField);
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 30));

        passLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        passLabel.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.passLabel.text")); // NOI18N
        getContentPane().add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 90, -1));

        passField.setBackground(new java.awt.Color(255, 204, 153));
        passField.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        passField.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.passField.text")); // NOI18N
        passField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        passField.setNextFocusableComponent(pass2Field);
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, 30));

        pass2Field.setBackground(new java.awt.Color(255, 204, 153));
        pass2Field.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.pass2Field.text")); // NOI18N
        pass2Field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(pass2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, 30));

        Pass2Label.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        Pass2Label.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.Pass2Label.text")); // NOI18N
        getContentPane().add(Pass2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 20));

        ageLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        ageLabel.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.ageLabel.text")); // NOI18N
        getContentPane().add(ageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, -1));

        ageField.setBackground(new java.awt.Color(255, 204, 153));
        ageField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ageField.setName("Edad"); // NOI18N
        ageField.setNextFocusableComponent(passField);
        getContentPane().add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 30));

        registerButton.setBackground(new java.awt.Color(255, 255, 204));
        registerButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        registerButton.setText(org.openide.util.NbBundle.getMessage(RegisterForm.class, "RegisterForm.registerButton.text")); // NOI18N
        registerButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 110, 30));

        passValidation.setBackground(new java.awt.Color(248, 248, 248));
        getContentPane().add(passValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 210, 120));

        nameAgeValidation.setBackground(new java.awt.Color(248, 248, 248));
        getContentPane().add(nameAgeValidation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 90));

        background.setBackground(new java.awt.Color(248, 248, 248));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mpm-retocao.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        GestorSwingKids gsk =new GestorSwingKids();
        Jugador newPlayer= new Jugador(String.valueOf(passField.getPassword()), Integer.parseInt(ageField.getText()),userNameField.getText());
        gsk.insertarJugador(newPlayer);
        RegisterCompleted registerCompleted=new RegisterCompleted();
        registerCompleted.setVisible(true);
        registerCompleted.setAlwaysOnTop(true);
        
        
        this.setVisible(false);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        
    }//GEN-LAST:event_userNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterForm dialog = new RegisterForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pass2Label;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel logo;
    private org.netbeans.validation.api.ui.swing.ValidationPanel nameAgeValidation;
    private javax.swing.JPasswordField pass2Field;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private org.netbeans.validation.api.ui.swing.ValidationPanel passValidation;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
