
package swingkids;

/**
 *
 * @author rafaelblancoaranda
 */
public class RegisterCompleted extends javax.swing.JFrame {

    /**
     * Creates new form RegisterCompleted
     */
    public RegisterCompleted() {
        initComponents();
        message2.setText("     Inicie Sesión para continuar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        messagePanel = new javax.swing.JPanel();
        blankSpace = new javax.swing.JTextArea();
        message1 = new javax.swing.JTextArea();
        message2 = new javax.swing.JTextArea();
        message3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setEditable(false);
        title.setBackground(new java.awt.Color(255, 204, 153));
        title.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title.setText(org.openide.util.NbBundle.getMessage(RegisterCompleted.class, "RegisterCompleted.title.text")); // NOI18N
        title.setToolTipText(org.openide.util.NbBundle.getMessage(RegisterCompleted.class, "RegisterCompleted.title.toolTipText")); // NOI18N
        title.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        title.setSelectionColor(new java.awt.Color(153, 153, 255));
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleKeyPressed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 204, 153));
        backButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        backButton.setText(org.openide.util.NbBundle.getMessage(RegisterCompleted.class, "RegisterCompleted.backButton.text")); // NOI18N
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        messagePanel.setBackground(new java.awt.Color(255, 255, 204));
        messagePanel.setFont(new java.awt.Font("Comic Sans MS", 2, 14)); // NOI18N
        messagePanel.setPreferredSize(new java.awt.Dimension(630, 630));
        messagePanel.setLayout(new java.awt.GridLayout(6, 6, 5, 5));

        blankSpace.setEditable(false);
        blankSpace.setBackground(new java.awt.Color(255, 255, 204));
        blankSpace.setColumns(20);
        blankSpace.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        blankSpace.setRows(5);
        blankSpace.setBorder(null);
        messagePanel.add(blankSpace);

        message1.setEditable(false);
        message1.setBackground(new java.awt.Color(255, 255, 204));
        message1.setColumns(20);
        message1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        message1.setRows(5);
        message1.setBorder(null);
        messagePanel.add(message1);

        message2.setEditable(false);
        message2.setBackground(new java.awt.Color(255, 255, 204));
        message2.setColumns(20);
        message2.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        message2.setRows(5);
        message2.setBorder(null);
        messagePanel.add(message2);

        message3.setEditable(false);
        message3.setBackground(new java.awt.Color(255, 255, 204));
        message3.setColumns(20);
        message3.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        message3.setRows(5);
        message3.setBorder(null);
        messagePanel.add(message3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        setLocation(evt.getXOnScreen() - 300, evt.getYOnScreen());
    }//GEN-LAST:event_titleMouseDragged

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void titleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleKeyPressed

    }//GEN-LAST:event_titleKeyPressed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCompleted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCompleted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCompleted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCompleted.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCompleted().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea blankSpace;
    private javax.swing.JTextArea message1;
    private javax.swing.JTextArea message2;
    private javax.swing.JTextArea message3;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
